# Generated by Django 5.0.7 on 2024-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(blank=True, default=None, help_text='NUMERO DE CARTÃO COMPLETO', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default=None, help_text='NOME', max_length=30, null=True)),
                ('data', models.DateField(blank=True, default=None, help_text='DATA', max_length=8, null=True)),
                ('lote', models.CharField(blank=True, default=None, help_text='LOTE', max_length=8, null=True)),
                ('quantidade_registro', models.CharField(blank=True, default=None, help_text='QDT DE REGISTROS', max_length=6, null=True)),
                ('numeracao_no_lote', models.CharField(blank=True, default=None, help_text='NUMERAÇÃO NO LOTE', max_length=8, null=True)),
                ('numero_cartao', models.CharField(blank=True, default=None, help_text='NUMERO DE CARTÃO COMPLETO', max_length=500, null=True)),
                ('unique', models.CharField(blank=True, default=None, help_text='IDENTIFICADOR UNICO', max_length=30, null=True)),
            ],
        ),
    ]
