# Generated by Django 5.0.7 on 2024-07-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileapi',
            name='unique',
            field=models.CharField(blank=True, default=None, help_text='IDENTIFICADOR UNICO', max_length=50, null=True),
        ),
    ]
